### ISSUE TITLE
Accordion, Popup Window

### ISSUE THREAD

**Issue by hanwa11** [t3brightside/containeritems#2]
If there is more than one accordion or popup window in different sections only the first one will work.

**Comment by t3brightside** [comment]
Thanks, indeed seems to be an issue. Will take a look at it soon...

**Comment by hanwa11** [comment]
wow great response time!

Von: Tanel Põld ***@***.***>
Gesendet: Sonntag, 23. April 2023 16:19
An: t3brightside/containeritems ***@***.***>
Cc: Waltenberger Hannes ***@***.***>; Author ***@***.***>
Betreff: Re: [t3brightside/containeritems] Accordion, Popup Window (Issue #2)


Thanks, indeed seems to be an issue. Will take a look at it soon...

**Comment by t3brightside** [comment]
No worries @hanwa11
Accordion should be fixed in dev version now.

Popups I see no problem with, seems to work just fine. Except it's still experimental and only works with opening buttons for now, not with RTE links or anything.
`<button name="cMyElementUid" class="c-popup-opener">text</button>`
